
#ifndef USERMANAGEMENT_VIEWRECRUITMENTSTATISTICS_CPP
#define USERMANAGEMENT_VIEWRECRUITMENTSTATISTICS_CPP

#include "ViewRecruitmentStatistics.h"


#endif //USERMANAGEMENT_VIEWRECRUITMENTSTATISTICS_CPP
