
#ifndef USERMANAGEMENT_VIEWJOBAPPLICATIONSTATISTICSUI_H
#define USERMANAGEMENT_VIEWJOBAPPLICATIONSTATISTICSUI_H


class ViewJobApplicationStatisticsUI {

};


#endif //USERMANAGEMENT_VIEWJOBAPPLICATIONSTATISTICSUI_H
