
#ifndef USERMANAGEMENT_VIEWJOBAPPLICATIONSTATISTICS_H
#define USERMANAGEMENT_VIEWJOBAPPLICATIONSTATISTICS_H


class ViewJobApplicationStatistics {

};


#endif //USERMANAGEMENT_VIEWJOBAPPLICATIONSTATISTICS_H
