#ifndef USERMANAGEMENT_VIEWRECRUITMENTSTATISTICSUI_H
#define USERMANAGEMENT_VIEWRECRUITMENTSTATISTICSUI_H


class ViewRecruitmentStatisticsUI {

};


#endif //USERMANAGEMENT_VIEWRECRUITMENTSTATISTICSUI_H
