
#ifndef USERMANAGEMENT_INQUIRECOMPANYRECRUITMENTS_CPP
#define USERMANAGEMENT_INQUIRECOMPANYRECRUITMENTS_CPP

#include "InquireCompanyRecruitments.h"


#endif //USERMANAGEMENT_INQUIRECOMPANYRECRUITMENTS_CPP
