
#ifndef USERMANAGEMENT_INQUIRECOMPANYRECRUITMENTS_H
#define USERMANAGEMENT_INQUIRECOMPANYRECRUITMENTS_H


class InquireCompanyRecruitments {

};


#endif //USERMANAGEMENT_INQUIRECOMPANYRECRUITMENTS_H
