
#ifndef USERMANAGEMENT_INQUIRECOMPANYRECRUITMENTSUI_H
#define USERMANAGEMENT_INQUIRECOMPANYRECRUITMENTSUI_H


class InquireCompanyRecruitmentsUI {

};


#endif //USERMANAGEMENT_INQUIRECOMPANYRECRUITMENTSUI_H
